model:
  base_learning_rate: 4.5e-6
  target: stable-diffusion.ldm.models.autoencoder.VQModel
  params:
    embed_dim: 4
    n_embed: 16384
    monitor: val/rec_loss

    ddconfig:
      attn_type: none
      double_z: false
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        n_classes: 1
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6
        codebook_weight: 1.0
        n_classes: null
        n_classes: 16384

data:
  target: CustomImagePickleDataset
  params:
    batch_size: 1
    num_workers: 1
    train:
      target: CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/MuaSlices/train
        size: 1024
    validation:
      target: CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/MuaSlices/train
        size: 1024

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
