logfile : /scratch/10122/thomaswynn7394/latentDiffusion/autoencoderTraining/tb_logs
model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    ckpt_path: /scratch/10122/thomaswynn7394/latentDiffusion/autoencoderTraining/kl-f8.ckpt
    # ckpt_path: /scratch/10122/thomaswynn7394/latentDiffusion/autoencoderTraining/lightning_logs/version_1910058/checkpoints/epoch=9-step=33340.ckpt
    #ckpt_path: /scratch/10122/thomaswynn7394/latentDiffusion/autoencoderTraining/lightning_logs/version_9_epochs/checkpoints/epoch=9-step=33340.ckpt
    embed_dim: 4
    lossconfig:
      target: loss.MSSSIM_Loss
      params:
        disc_start: 100000000000000
        kl_weight: 1.0e-06
        disc_weight: 0
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: CustomImagePickleDataset
  params:
    batch_size: 5
    num_workers: 5
    persistent_workers: True
    train:
      target: CustomImagePickleDataset
      params:
        data_root: /work/10122/thomaswynn7394/ls6/MuaSlices/train
        size: 1024
    validation:
      target: CustomImagePickleDataset
      params:
        data_root: /work/10122/thomaswynn7394/ls6/MuaSlices/val
        size: 1024

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: True
  trainer:
    max_epochs: 15
    gpus: 3
    precision: 32
    log_every_n_steps: 100
