model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: models.diffusion.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        use_svd : True
        k : 1000 # MUST MATCH FIRST STAGE CONFIG k
        full_latent_dim : [4,32,32] #This is only when using SVD in first stage, so that convolutions can apply in unet
        U_path : "/workspace/thomas/latentDiffusion/autoencoderTraining/scripts/U.pt"
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: models.autoencoder_linear_compression.AutoencoderKL
      params:
        k : 1000
        U_path : /workspace/thomas/latentDiffusion/autoencoderTraining/scripts/U.pt
        monitor: val/rec_loss
        ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/tb_logs/default/U2000/checkpoints/epoch=1-step=13333.ckpt # set to most recent in tb_logs
        #ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/lightning_logs/version_166/checkpoints/epoch=0-step=9999.ckpt
        # ckpt_path : /workspace/thomas/latentDiffusion/epoch=1-step=6668.ckpt
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 5
    train:
      target: data.loader.CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/train
        size: 1024
    validation:
      target: data.loader.CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/val
        size: 1024

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
  trainer:
    gpus : "0"
    max_epochs: 3
    precision: 32
    log_every_n_steps: 50