logfile : /workspace/thomas/latentDiffusion/autoencoderTraining/tb_logs
model:
  base_learning_rate: 1.0e-05
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/tb_logs/default/full_autoencoder/checkpoints/epoch=9-step=12499.ckpt
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    latent_ae_config: 
      embed_dim: 4
      ddconfig:
        double_z: true
        z_channels: 4
        resolution: 32
        in_channels: 4
        out_ch: 4
        ch: 128
        ch_mult:
        - 1
        - 1
        num_res_blocks: 1
        attn_resolutions: []
        dropout: 0.0


data:
  target: CustomImagePickleDataset
  params:
    batch_size: 16
    num_workers: 5
    train:
      target: CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/train
        size: 1024
    validation:
      target: CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/val
        size: 1024
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
  trainer:
    max_epochs: 10
    gpus: 1
    precision: 32
    log_every_n_steps: 50
