model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: models.diffusion.ddpm_vanilla.LatentDiffusion
  params:
    #ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/weights/celeba.ckpt
    ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/weights/diffusion_32_e30.ckpt
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2  
    first_stage_key: "image"
    cond_stage_key: "image"
    parameterization: "eps"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: models.diffusion.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: models.autoencoder_downsample.AutoencoderKL
      params:
        monitor: val/rec_loss
        ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/weights/kl-f8-10.ckpt # set to most recent in tb_logs
        #ckpt_path: /workspace/thomas/latentDiffusion/autoencoderTraining/lightning_logs/version_166/checkpoints/epoch=0-step=9999.ckpt
        # ckpt_path : /workspace/thomas/latentDiffusion/epoch=1-step=6668.ckpt
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 5
    train:
      target: data.loader.CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/train
        
    validation:
      target: data.loader.CustomImagePickleDataset
      params:
        data_root: /workspace/thomas/latentDiffusion/autoencoderTraining/data/MuaSlices/val
       

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 3000  # Logs every 3000 batches
        max_images: 4
        clamp: true
        log_images_kwargs:
          N: 8  # Number of images to log
          n_row: 4  # Number of rows in the grid for logging
          sample: true  # Whether to sample images or not
          ddim_steps: 200  # Number of DDIM steps
          ddim_eta: 1.0  # DDIM eta parameter
          quantize_denoised: true  # Whether to quantize the denoised images
          inpaint: false  # Whether to perform inpainting
          plot_denoise_rows: false  # Whether to plot denoising steps
          plot_progressive_rows: true  # Whether to plot progressive denoising rows
          plot_diffusion_rows: true  # Whether to plot diffusion steps

  trainer:
    gpus : "0"
    max_epochs: 30
    precision: 32
    log_every_n_steps: 10000